### PR TITLE
Only update the TIR compiler's return stack for inlined calls.

### LINKED ISSUE #188: Undefined variable errors in TIR compiler.
```
      #[test]                                                                                                                                                                                                       
      fn recursion() {                                                                                                                                                                                        
          struct IO(usize);                                                                                                                                                                                         
                                                                                                                                                                                                                    
          fn recurse(c: usize) -> usize {                                                                                                                                                                           
              if c == 0 {                                                                                                                                                                                           
                  42                                                                                                                                                                                                
              } else {                                                                                                                                                                                              
                  recurse(c - 1)                                                                                                                                                                                    
              }                                                                                                                                                                                                     
          }                                                                                                                                                                                                         
                                                                                                                                                                                                                    
          #[interp_step]                                                                                                                                                                                            
          fn interp_step(io: &mut IO) {                                                                                                                                                                             
              io.0 = recurse(1);                                                                                                                                                                                    
          }                                                                                                                                                                                                         
                                                                                                                                                                                                                    
          let mut inputs = IO(0);                                                                                                                                                                                   
          let th = start_tracing(TracingKind::HardwareTracing);                                                                                                                                                     
          interp_step(&mut inputs);                                                                                                                                                                                 
          let sir_trace = th.stop_tracing().unwrap();                                                                                                                                                               
          let tir_trace = TirTrace::new(&*SIR, &*sir_trace).unwrap(); 
    }
```

Gives:
```
thread 'tests::spilling_simple' panicked at 'undefined local: $5 in guard($5+8, bool(false), <_ZN9ykcompile5tests15spilling_simple7recurse17h07a58b090b285788E, 1>, [])', yktrace/src/tir.rs:84:21
```

### PR DESCRIPTION
**Pull request by vext01**
This change fixes a bug where we'd update the return stack for external
calls (for example, things marked `#[do_not_trace]`). This is wrong
because we will never see a corresponding Return terminator for the
callee, and then some poor unrelated (and unsuspecting) Return ends up
popping a garbage value off of the return stack.

The fix is to only push to the return stack if the call is to be
inlined.

Fixes #188.

### CODE REVIEW

File: yktrace/src/tir.rs [hunk 1]
```diff
@@ -41,6 +41,11 @@ impl<'a, 'm> TirTrace<'a, 'm> {
         // Maps symbol names to their virtual addresses.
         let mut addr_map: HashMap<String, u64> = HashMap::new();
 
+        // We use a stack of IPlaces to keep track of storage for return values of inlined calls.
+        // When we encounter the Return terminator of a call that's being inlined into the trace,
```
Comment (ltratt) [inline yktrace/src/tir.rs:45]: This sentence is very hard to parse (I eventually worked out it out, but it took me a few reads). I'd suggest starting with what it *does* not what it *doesn't do*. Something like "We need to convert `return`s from inlined functions into stores" maybe?

**Comment by ltratt** [comment]
On a related note to my pedantic comment, when we come to merge, can we change the commit title from "Fix a nasty bug in the TIR compiler's return stack" to something like "Convert returns in inlined functions to stores"?

File: yktrace/src/tir.rs (hunk 1 above)
Comment (vext01) [reply yktrace/src/tir.rs]: Try 968e2a8, is this clearer?

Comment (ltratt) [reply yktrace/src/tir.rs]: I'm not sure what "To avoid unnecessary stores" has to do with anything?

Comment (vext01) [reply yktrace/src/tir.rs]: This is effectively an optimisation that eliminates one store.

Instead of:
```
callee:
  $x = return value
caller:
  $y = $x
```

You get:
```
callee:
   $y = return value
```

Comment (ptersilie) [reply yktrace/src/tir.rs]: What Edd said. This is an optimisation that assigns the return value of an inlined function immediately to the destination of the function call instead of going via the return local (`$0`).

Comment (ltratt) [reply yktrace/src/tir.rs]: Ah, then I misunderstood what's going on. Silly question: why are we doing this optimisation here? Wouldn't it be better to leave this to a generic optimisation pass?

Comment (bjorn3) [reply yktrace/src/tir.rs]: I would guess as it is very common and is much cheaper to do in this case than the general case.

Comment (ltratt) [reply yktrace/src/tir.rs]: I'm asking partly for a generic reason: the problem with "early" optimisations like these is that they tend to introduce bugs (like the one cleared up by this PR). Then we have to ask whether they're worth it, or, at least, whether they're worth doing now. I'm open-minded in this case!

Comment (vext01) [reply yktrace/src/tir.rs]: Since it's implemented, I'd say leave it for now.

Comment (ltratt) [reply yktrace/src/tir.rs]: Are we reasonably confident that a) there aren't other edge cases or b) that we've thought through those edge cases?

Comment (ptersilie) [reply yktrace/src/tir.rs]: At the time (when we didn't have `do_not_trace` yet) it was a very simple optimisation which essentially did this:
```
$0 = $1;
$5 = $0;
```
becomes
```
$5 = $1;
```
So there wasn't too much to think about in terms of edge cases.

**Comment by ptersilie** [comment]
Please squash.

**Comment by vext01** [comment]
If we are not spinning this as an optimisation, I think I should update the comment describing the return stack.

**Comment by ltratt** [comment]
That would be good, thanks @vext01!

**Comment by vext01** [comment]
Try this. This was actually quite hard to put into words!

File: yktrace/src/tir.rs [hunk 2]
```diff
@@ -41,10 +41,10 @@ impl<'a, 'm> TirTrace<'a, 'm> {
         // Maps symbol names to their virtual addresses.
         let mut addr_map: HashMap<String, u64> = HashMap::new();
 
-        // To avoid unnecessary stores, inlined function calls store their return value directly
-        // into its final resting place chosen by the caller. To make this happen, we use a stack
-        // of IPlaces to keep track of storage for our return values. The `Call` pushes to the
-        // stack, and the corresponding `Return` pops.
+        // A stack to keep track of where to store return values of inlined calls. When we
+        // encounter `$x = Call(...)` we push `$x` to the stack so that later, when we encounter
+        // the corresponding Return, we can find the correct place to store the return value to (by
```
Comment (ltratt) [inline yktrace/src/tir.rs:46]: Is the `to` stray?

File: yktrace/src/tir.rs [hunk 3]
```diff
@@ -41,10 +41,10 @@ impl<'a, 'm> TirTrace<'a, 'm> {
...
+        // popping from the stack). It has to be a stack to allow for nested inlined calls.
```
Comment (ltratt) [inline yktrace/src/tir.rs:47]: I think this last sentence is redundant (it's implied by the first sentence)?

Comment (vext01) [reply yktrace/src/tir.rs:47]: Fair enough.

File: yktrace/src/tir.rs (hunk 2 above)
Comment (vext01) [reply yktrace/src/tir.rs:46]: This one?

> the correct place to store the return value to

I almost went with `into`, would that help?

Comment (ltratt) [reply yktrace/src/tir.rs:46]: I think we can just drop the "to" entirely? It's a bit hard to parse with the the following `(by`.

**Comment by vext01** [comment]
Give that a go.

**Comment by ltratt** [comment]
Please squash (and I guess you'll want to update the commit message too).

**Comment by vext01** [comment]
splat.
